---
abstract: 'Hook registrations at fork(2)'
author:
  - 'Fuji, Goro (gfx)'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::SharedFork: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POSIX::AtFork
name: POSIX-AtFork
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
x_contributors:
  - 'Alexey Mashanov <amashanov@corp.mail.ru>'
  - 'Nikolay Shulyakovskiy (nikolas) <shulyakovskiy@corp.mail.ru>'

